# Generated by Django 5.1.4 on 2025-04-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='downloadable_file',
            field=models.FileField(blank=True, null=True, upload_to='event_files/'),
        ),
    ]
