# Generated by Django 5.1.4 on 2025-04-15 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_organizer_user_is_organizer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название викторины"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Викторина",
                "verbose_name_plural": "Викторины",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "Одиночный выбор"),
                            ("multiple", "Множественный выбор"),
                        ],
                        default="single",
                        max_length=10,
                        verbose_name="Тип вопроса",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="quiz_images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "option_1",
                    models.CharField(max_length=200, verbose_name="Вариант 1"),
                ),
                (
                    "option_2",
                    models.CharField(max_length=200, verbose_name="Вариант 2"),
                ),
                (
                    "option_3",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Вариант 3"
                    ),
                ),
                (
                    "option_4",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Вариант 4"
                    ),
                ),
                (
                    "correct_answers",
                    models.CharField(
                        max_length=50,
                        verbose_name="Правильные ответы (индексы через запятую, например: 1 или 1,2)",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="events.quiz",
                        verbose_name="Викторина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_answers",
                    models.CharField(
                        max_length=50,
                        verbose_name="Выбранные ответы (индексы через запятую)",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата ответа"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.question",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ пользователя",
                "verbose_name_plural": "Ответы пользователей",
            },
        ),
    ]
